services:
  - type: web
    name: scalable-backend-api
    runtime: node
    plan: free
    region: oregon
    branch: main
    buildCommand: npm install --omit=dev
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /api/docs
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
      - key: MONGO_URI
        sync: false
